### ISSUE TITLE
Org-Journal is a community project

### ISSUE THREAD

**Issue by bastibe** [bastibe/org-journal#144]
Dear @vkazanov @cslux @TinaRussell, I would like to honor your contributions to org-journal, and invite you to become co-maintainers of org-journal. This invitation comes with no obligations whatsoever, but is simply a recognition of your contributions to org-journal, and its community.

As you know, I did not formally start org-journal, either, but instead based it on https://www.emacswiki.org/emacs/PersonalDiary, by mtvoid. But org-journal would not be what it is today without mtvoid's contributions, or yours, or mine. It is truly a community project.

On behalf of everyone using org-journal, I thank you for your work on this project!

**Comment by vkazanov** [comment]
@bastibe thanks for all the maitenance work you did on the project! I've been using it for a few years now to great success and satisfaction.

Any special plans for the project..?

**Comment by cslux** [comment]
@bastibe Thanks for the invitation, and your work! 

Hello everybody!

I have some ideas in my mind. 

1. Add some code to transform journals between daily/weekly/monthly/yearly journal files.
2. Keep track of the journal dates, either persistently by saving it to disk, or just for the duration of the Emacs session. 
If there are lot's of journal entries some stuff can get pretty slow, e.g. moving around in the calendar. 
If `org-journal-encrypt-journal` is set to `t` you notice it already even for a single file. Since I personally encrypt my journal files. I'm open to implement that feature. I prefer the persistent variant, and save the dates into, e.g. ~/.emacs.d/.org-journal-dates.el. As a first step I'll write some code which only searches in the journal files (weekly/monthly/yearly), between the calendar date range currently visible. On that way, I may find other bottlenecks.

**Comment by bastibe** [comment]
> Any special plans for the project..?

No, as I said, this comes with no obligations whatsoever. Org-Journal works absolutely beautifully for me.

> I have some ideas in my mind.

These are great ideas! Expanded encryption support in particular seems to be requested quite often.

**Comment by cslux** [comment]
Pinned it!
