### ISSUE TITLE
org-journal-carryover-items cannot be nil

### ISSUE THREAD

**Issue by DuCorey** [bastibe/org-journal#176]
Hi,
The guide recommends setting `org-journal-carryover-items` to `nil` to disable carryover items. This is currently bugged. The current check is for empty strings with `string-blank-p`. This function cannot operate on `nil`.

This behavior was changed in #168. This was done because the previous commentator claimed to not have been able to set the value of `org-journal-carryover-items` to `nil` using the customize interface. I'm unsure why the user was not able to do so, as it is definitely possible to do and intended behavior. 

I recommend either of these solutions:

1. Reverting #168.

2. Indicating in the README that the correct way of disabling carryover items is to set the value to an empty string `(setq org-journal-carryover-items "")`.

3. Checking for either `nil` or the empty string `""`. (Is this even possible?)

Thanks,
Corey

**Comment by cslux** [comment]
@DuCorey The readme is wrong. The correct way is to set `org-journal-carryover-items` to an empty string `""`. However, we could of course also check if the variable is nil, just in case. I will update the readme and also will check if the variable is nil.

Setting the variable to nil in the customize interface is not possible due to the fact that `org-journal-carryover-items` is of type `'string`.  Of course you could set it programmatically to nil.

Thanks for pointing this out. 

cheers,
Chris
