### ISSUE TITLE
Use C-c j as prefix for org-journal-mode

### ISSUE THREAD

**Issue by cslux** [bastibe/org-journal#255]
Some bindings overwrite org-mode bindings like C-c C-s (org-journal-search -> org-schedule).

**Comment by bastibe** [comment]
According to https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html, we shouldn't bind to C-c <letter>.

I think our safest bet would be to convert org-journal to a minor mode, and use a C-c <punctuation> as prefix.

We would need to communicate this very clearly, however, as it would introduce a breaking change to existing users.

**Comment by cslux** [comment]
Yeah right. I will do a little research an that. Coming back when I know more.

**Comment by vcg3rd** [comment]
In Emacs 26.3, org-mode 9.1.9 if I C-h k C-c C-j I get "C-c C-j runs the command org-goto (found in org-mode-map), which is an interactive compiled Lisp function in ‘org.el’.

I haven't used org-journal in a couple of weeks. I'm still trying to tweak it how I want, but I don't think it did that last time I used it. (No emacs related updates since then.)
