### ISSUE TITLE
Create new entry on current journal buffer

### ISSUE THREAD

**Issue by k0377** [bastibe/org-journal#29]
Thank you for this great extension!

I really like it so far, but there is a problem I dont know how to solve.

I would like to add another entry in my current open journal file. But `C-c C-j` will not work then, instead org-goto will open. The only way to add a new entry then, is to change the buffer to another file and hit `C-c C-j` again.

Any workaround or is this the supposed way of org-journal?

Thanks a lot!

**Comment by bastibe** [comment]
This one never occurred to me, since I personally use `C-c j` for this (`(global-set-key (kbd "C-c j") 'org-journal-new-entry)`). 

Still, this is easy to fix. ffb9558fad7b410f64abbfe17f38335cdedda14f sets `C-c C-j` in `org-journal-mode`. It still won't work in regular `org-mode`, but your use case should be covered. The change is uploaded to marmalade, and melpa/melpa-stable should update, soon, too.

**Comment by k0377** [comment]
Just tried, works great, thank you for the fast support! :baby_bottle:
