### ISSUE TITLE
org-journal default path conflicting with user set path on update

### ISSUE THREAD

**Issue by k9zoli** [bastibe/org-journal#57]
Hi, 

Just noticed after last melpa update that the org-journal default path overrides the user set path after update. I am not sure this is an issue to post here (never interacted like this before) - I thought I'd signal about it; it would be nice if somehow an update would not require ulterior user interaction regarding custom path settings - if possible.

**Comment by bastibe** [comment]
Thank you for the heads-up. I am currently on vacation and won't be able to look into it. I will investigate once I get back home.

Could you describe in a little more detail how org-journal overrides your path? Please tell me your operating system, and your org-journal related settings in your init.el or .emacs file.

**Comment by k9zoli** [comment]
Thanks :)

Now that you asked about init.el org-journal related settings - well, looking into it I had nothing (and it worked even so, starting a new entry from calendar view only). I vaguely remember getting into org-journal very tired, without paying too much attention. What I did then was to search for "~/Documents/journal/" and add my own path instead (at line 106) in org-journal.el.

Now I added this to init.el:
(require 'org-journal)                                             
(setq journal-dir "~/org/journal") 
Much likely it will now work on a subsequent update. 
Sorry for the mess, I am not a programmer and the "journal-dir is also a customizable variable. The default value for journal-dir is ~/Documents/journal/." comment/explanation from the beginnings of org-journal.el did not really ring any bell to me. I now looked it up how to define a variable (setq) and hopefully it is all right the way I wrote up here. 
Please close this when you see fit as there is no issue at all (except for the fact that someone who is not a programmer does not see - without an example as babies :)) - what and how exactly should be in init.el.
Have a nice vacation! Happy 2016! :)

**Comment by k9zoli** [comment]
Update:
With this in my init.el:

(require 'org-journal)
(setq journal-dir "~/org/journal") 

 - it seems that it is still not working as it should. 
I get this error message:

Warning (initialization): An error occurred while loading `/home/*username*/.emacs.d/init.el':
File error: Cannot open load file, no such file or directory, org-journal
To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the `--debug-init' option to view a complete error backtrace.

What exactly should I putin init.el so this message does not appear?
I can still start a new entry with C-c C-j, nut this error message obviously means that something is not correct.

Starting Emacs with '--debug-init' option it says:

Debugger entered--Lisp error: (file-error "Cannot open load file" "no such file or directory" "org-journal")
  require(org-journal)
  eval-buffer(#<buffer  *load*> nil "/home/*username*/.emacs.d/init.el" nil t)  ; Reading at buffer position 163
  load-with-code-conversion("/home/*username*/.emacs.d/init.el" "/home/*username*/.emacs.d/init.el" t t)
  load("/home/*username*/.emacs.d/init" t t)
  #[0 "^H\205\262^@     \306=\203^Q^@\307^H\310Q\202;^@ \311=\204^^^@\307^H\312Q\202;^@\313\307\314\315#\203*^@\316\202;^@\313\307\314\317#\2$
  command-line()
  normal-top-level()

Location of org-journal related files on my computer:
~/.emacs.d/elpa/org-journal-20151228.603

**Comment by bastibe** [comment]
Thank you for this further investigation. Since org-journal in general is working in your Emacs, you should not need to `(require 'org-journal)` manually. Without the `require`, your init.el and `setq` should work as intended.

However, it might be easier to use `customize` instead to change your `org-journal-dir`. Select *Options* --> *Customize* --> *Options Matching* from your menubar, then type `org-journal`, and you should see a clickable interface to change and save `org-journal-dir`. Alternatively, type `M-x`, then `customize` and use the search box to search for `org-journal` to access the same page.

In general, the Emacs packaging system assumes that you do not change the contents of the packages themselves. Instead, most packages define customizable options (such as `org-journal-dir`), which can be changed either in your init.el or through `customize`. This is the preferred way of changing the behavior of Emacs packages.

As a side note, there are many ways to change things in Emacs, and `customize` only scratches the surface of what is possible. One of the main features of Emacs is that absolutely everything can be changed by the user. And none of these require you to change the original source code.

Did this solve your issue?

**Comment by k9zoli** [comment]
Interestingly (and now I am completely confused regarding some aspects) - now journal and all its keybindings seem to work without any init.el customizations. 
The above lines I put in init.el still keep giving me the error on startup, so I commented them out and org-journal works.
I was not aware of customization possibilities in the menubar, Emacs runs in Gnome Terminal stripped down to menu-less view here and rarely in graphic mode. But I get the point, it is worth looking into the menus once in a while. I guess it was scary all the time looking into the mirad of options there, that's why life felt better without. 

Thanks for the feedbacks!

Issue solved (I just don't know how it happened) - no more problems.

**Comment by k9zoli** [comment]
Should I close or you do it?
