### ISSUE TITLE
Option to add entries past midnight to previous day with org-extend-today-until?

### ISSUE THREAD

**Issue by namdnguyen** [bastibe/org-journal#61]
This option would be helpful for those who work late nights past midnight and want journal entries to be logged on the journal for the date before midnight. Org-mode already provides support for extending today, so maybe have an option to toggle whether to use that time or go with the default of midnight?

**Comment by bastibe** [comment]
Interesting idea. I'll look into it, and see how difficult this would be to implement.

**Comment by bastibe** [comment]
Sorry that this is taking a while, but my spare time is limited as of late.

**Comment by leezu** [comment]
I'd also like to express "interest" in this features. (No worries / pressure though.)

**Comment by nickanderson** [comment]
+1

**Comment by bastibe** [comment]
Is anyone in here interested in trying to implement this? Pull requests would be very welcome!

**Comment by TinaRussell** [comment]
I would really love this feature because the “Tina day” definitely ends somewhere past midnight.
What functions would need to be changed? I’ve long been tempted to take a swing at this, but I’m an Emacs/Elisp newb and I’d be afraid that changing one thing would collapse the whole org-journal edifice.

**Comment by bastibe** [comment]
Wow, a lot of people seem to want this!

I implemented it in the latest version. Can you check that it works as intended? If you can confirm that it works, I'll push it to marmalade and melpa stable.

**Comment by TinaRussell** [comment]
It’s having problems for me—it works as intended, except that entries past midnight (but before the org-extend-today-until hour) have a blank datestamp.
The problem seems to happen in here:

`      (when should-add-entry-p
        (unless (eq (current-column) 0) (insert "\n"))
        (let ((timestamp (if (= (time-to-days (current-time)) (time-to-days time))
                             (format-time-string org-journal-time-format)
                           "")))
          (insert "\n" org-journal-time-prefix timestamp))
        (run-hooks 'org-journal-after-entry-create-hook))`

The “if” statement returns nil, so the timestamp variable is set to "". This doesn’t seem to happen for the rest of the day, though.

**Comment by bastibe** [comment]
Is this issue resolved?

**Comment by bastibe** [comment]
Cool!
