### ISSUE TITLE
Issues when in auctex mode and a suggestion

### ISSUE THREAD

**Issue by x61** [bastibe/org-journal#63]
The C-c C-j command does not bring up journal in all major modes. When using latex, for example, this key binding does not bring up journal for entry. Is there a way to force this key bind to work in all (major/minor) mode?

Also I know that in org-capture, the key binding C-c C-c closes the capture buffer. Is it possible to implement the idea in org-journal? I know  this key bind is used to assign tags but that only happens when at a heading (*, **,***, etc) line. You can implement it to the effect that when not at a heading line and the C-c C-c key is pressed, the journal closes.

**Comment by bastibe** [comment]
As for your first comment, I am very aware of that, but I don't see a way of circumventing that, since there are some restrictions on which key bindings a major mode might use. I recommend you `(global-set-key (kbd "C-c j") 'org-journal-new-entry)`, since `C-c <single-letter>` is reserved for user-created key bindings.

**Comment by bastibe** [comment]
As for your second comment, you could easily `(define-key org-journal-mode-map (kbd "C-c C-c") 'delete-window)`. Since this command is already easily accessible at `C-x 0`, I don't think that we need a separate key binding for it in org-journal, though.

Or did you have something else in mind for that?

**Comment by x61** [comment]
For your second respond, is it possible to make the buffer close with the command (C-c C-c)  only when on a line with no stars (*)? I want to still have the ability to tag a heading with the `C-c C-c` command when at a heading.

**Comment by x61** [comment]
Please ignore my previous comment. I just assigned a different key binding to close the journal-mode buffer. Thank you.
